---
- name: Kubeadm reset v1.11 or later
  command: kubeadm reset -f
  tags: k8s-worker

- name: For kubelet api
  firewalld:
    port: "10250/tcp"
    permanent: true
    state: enabled
    zone: internal

- name: For NortPort Service
  firewalld:
    port: "30000-32767/tcp"
    permanent: true
    state: enabled
    zone: internal

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes

