---
- name: Kubeadm reset v1.11 or later
  command: kubeadm reset -f
  tags: k8s-master

- name: Kubeadm init
  command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ node_ip }}"
  tags: k8s-master

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  tags: k8s-master

- name: Copy join command to sync directory
  copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: /tmp/join-command.sh
    mode: 0777
  tags: k8s-master

- name: Daemon-reload and restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
  tags: k8s-master

## Create kubeconfig
- name: Mkdir kubeconfig
  file:
    path:  /home/k8s/.kube
    state: directory
    owner: k8s
    group: wheel
    mode:  '0755'

## Copy admin.conf
#- name: Chmod admin.conf
#  file:
#    path:  /etc/kubernetes/admin.conf
#    owner: k8s
#    group: wheel
#    mode:  '0600'

- name: Copy config to home dir
  copy:
    src:  /etc/kubernetes/admin.conf
    dest: /home/k8s/.kube/config
    owner: k8s
    group: wheel
    mode:  '0600'
    remote_src: yes

- name: Append bashrc
  shell: echo 'export KUBECONFIG=/home/k8s/.kube/config' >> /home/k8s/.bashrc
  tags: k8s-master

  #- name: Install wget
  #  yum:
  #    name: wget
  #    state: latest
  #  tags: k8s-master

- name: Install flannel
  get_url:
    url: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
    dest: /tmp/kube-flannel.yml
  tags: k8s-master

- name: Deploy Flannel
  command: kubectl apply -f /tmp/kube-flannel.yml
  become_user: k8s
  tags: k8s-master

- name: For Kuberbeters api server
  firewalld:
    port: "6443/tcp"
    permanent: true
    state: enabled
    zone: internal

- name: For etcd server client
  firewalld:
    port: "2379-2380/tcp"
    permanent: true
    state: enabled
    zone: internal

- name: For kubelet api
  firewalld:
    port: "10250/tcp"
    permanent: true
    state: enabled
    zone: internal

- name: For kube-scheduler
  firewalld:
    port: "10251/tcp"
    permanent: true
    state: enabled
    zone: internal

- name: For kube-controller-manager
  firewalld:
    port: "10252/tcp"
    permanent: true
    state: enabled
    zone: internal

- name: For flannel
  firewalld:
    port: "8285/udp"
    permanent: true
    state: enabled
    zone: internal

- name: For flannel
  firewalld:
    port: "8472/udp"
    permanent: true
    state: enabled
    zone: internal

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes

- name: Daemon-reload and restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
  tags: k8s-master

