apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-volume
  namespace: monitoring
spec:
  storageClassName: "manual"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
#   hostPath:
#     path: /home/pi/usb/usb1/grafana
  nfs:
    server: 10.1.0.30
    path: /mnt/share/nfs/grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
