apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus-service
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
